spring:
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB.URL}
    USERNAME: ${DB.USERNAME}
    PASSWORD: ${DB.PASSWORD}
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        format_sql: true

